### ISSUE TITLE
Chiara doesn't play :-(

### ISSUE THREAD

**Issue by Ederion70** [dl1hrc/svxlink-sounds-it_IT-chiara#1]
Hi Adi,
I beg your pardon. I downloaded sounds chiara and I unzipped all directories in one named it_IT, but it doesn't play and I have a lot of errors like: "*** WARNING: Illegal WAV file header in "/usr/local/share/svxlink/sounds/it_IT/Default/activating.wav". "fmt" subchunk size is not 16: /usr/local/share/svxlink/sounds/it_IT/Default/activating.wav".
How can I solve it?
Thank ypu very very much!!

**Comment by dl1hrc** [comment]
Hm, this files are sampled with 22050Hz. I will see to provide a set with 16000 Hz sample rate.
73s de Adi / DL1HRC

**Comment by dl1hrc** [comment]
please could you make:
```
git pull
git checkout svxlink-sounds-it_IT-chiara-16k
```
should work now.

73s de Adi / DL1HRC

**Comment by Ederion70** [comment]
Hi Adi,
I tryed the 2 commands you suggested, but I have this error: "fatal: not a git repository (or any of the parent directories): .git
Maybe I make a mistake, but I don't know what!
Thank you!

Today is the first of new year so Happy New Year!!

**Comment by dl1hrc** [comment]
per favore, ivialo una email a dl1hrc {at} gmx {dot} de

73s de Adi / DL1HRC
